const {
  onCall,
  HttpsError,
} = require(
  "firebase-functions/v2/https"
);

const {
  initializeApp,
} = require(
  "firebase-admin/app"
);

const {
  getFirestore,
  FieldValue,
} = require(
  "firebase-admin/firestore"
);

const {
  getStorage,
} = require(
  "firebase-admin/storage"
);

const sharp =
  require(
    "sharp"
  );

initializeApp();

const db =
  getFirestore();

const bucket =
  getStorage().bucket();

const THUMBNAIL_MAX_SIZE =
  800;

const THUMBNAIL_QUALITY =
  82;

const PROCESSING_CONCURRENCY =
  5;

/*
 * =========================================================
 * GENERATE MISSING THUMBNAILS
 * =========================================================
 *
 * Called by the Photos Admin page.
 *
 * The server:
 *
 * 1. Verifies the signed-in user is an admin.
 * 2. Finds photos in the selected album.
 * 3. Finds photos without thumbnailPath.
 * 4. Downloads the source directly inside Firebase.
 * 5. Resizes with sharp.
 * 6. Uploads the JPEG thumbnail.
 * 7. Updates the Firestore photo document.
 *
 * Nothing is downloaded to the browser.
 */

exports.generateMissingPhotoThumbnails =
  onCall(
    {
      region:
        "us-central1",

      memory:
        "2GiB",

      timeoutSeconds:
        540,
    },

    async (
      request
    ) => {
      /*
       * AUTH
       */

      if (
        !request.auth
      ) {
        throw new HttpsError(
          "unauthenticated",
          "You must be signed in."
        );
      }

      const weddingId =
        String(
          request.data?.weddingId ||
            ""
        ).trim();

      const albumId =
        String(
          request.data?.albumId ||
            ""
        ).trim();

      if (
        !weddingId
        ||
        !albumId
      ) {
        throw new HttpsError(
          "invalid-argument",
          "weddingId and albumId are required."
        );
      }

      /*
       * VERIFY ADMIN
       */

      const adminSnapshot =
        await db
          .doc(
            `weddings/${weddingId}/admins/${request.auth.uid}`
          )
          .get();

      if (
        !adminSnapshot.exists
        ||
        adminSnapshot.data()
          ?.active !==
          true
      ) {
        throw new HttpsError(
          "permission-denied",
          "You do not have permission to manage these photos."
        );
      }

      /*
       * VERIFY ALBUM
       */

      const albumSnapshot =
        await db
          .doc(
            `weddings/${weddingId}/photoAlbums/${albumId}`
          )
          .get();

      if (
        !albumSnapshot.exists
      ) {
        throw new HttpsError(
          "not-found",
          "The selected photo album does not exist."
        );
      }

      /*
       * LOAD PHOTOS
       */

      const photoSnapshot =
        await db
          .collection(
            `weddings/${weddingId}/photos`
          )
          .where(
            "albumId",
            "==",
            albumId
          )
          .get();

      const photos =
        photoSnapshot.docs
          .map(
            (
              document
            ) => ({
              id:
                document.id,

              ref:
                document.ref,

              ...document.data(),
            })
          )
          .filter(
            (
              photo
            ) =>
              !photo.thumbnailPath
          );

      /*
       * NOTHING TO DO
       */

      if (
        photos.length ===
        0
      ) {
        return {
          total:
            0,

          successful:
            0,

          failed:
            0,

          skipped:
            0,

          failures:
            [],

          skippedPhotos:
            [],
        };
      }

      /*
       * PROCESS
       */

      const failures =
        [];

      const skipped =
        [];

      let successful =
        0;

      await runWithConcurrency(
        photos,

        PROCESSING_CONCURRENCY,

        async (
          photo
        ) => {
          try {
            /*
             * HEIC originals are not sent
             * directly to Sharp here.
             *
             * If the photo already has the
             * PNG display copy generated by
             * the browser, use that.
             *
             * Otherwise skip it so it can be
             * repaired first from the admin
             * page.
             */

            if (
              isHeicPhoto(
                photo
              )
              &&
              !hasSeparateDisplayCopy(
                photo
              )
            ) {
              skipped.push({
                fileName:
                  photo.fileName ||
                  photo.id,

                reason:
                  "HEIC photo needs a browser-compatible display copy first.",
              });

              return;
            }

            /*
             * Use display copy when available.
             * Otherwise use original.
             */

            const sourcePath =
              hasSeparateDisplayCopy(
                photo
              )
                ? photo.displayPath
                : photo.storagePath;

            if (
              !sourcePath
            ) {
              throw new Error(
                "Photo has no Storage path."
              );
            }

            /*
             * DOWNLOAD DIRECTLY INSIDE
             * GOOGLE CLOUD
             */

            const sourceFile =
              bucket.file(
                sourcePath
              );

            const [
              sourceBuffer,
            ] =
              await sourceFile.download();

            /*
             * RESIZE
             *
             * rotate() applies the image's
             * EXIF orientation before resizing.
             */

            const thumbnailBuffer =
              await sharp(
                sourceBuffer,
                {
                  failOn:
                    "none",
                }
              )
                .rotate()
                .resize({
                  width:
                    THUMBNAIL_MAX_SIZE,

                  height:
                    THUMBNAIL_MAX_SIZE,

                  fit:
                    "inside",

                  withoutEnlargement:
                    true,
                })
                .flatten({
                  background:
                    "#ffffff",
                })
                .jpeg({
                  quality:
                    THUMBNAIL_QUALITY,

                  mozjpeg:
                    true,
                })
                .toBuffer();

            /*
             * THUMBNAIL PATH
             */

            const originalFileName =
              getStorageFileName(
                photo.storagePath
                ||
                sourcePath
              );

            const thumbnailName =
              replaceExtension(
                originalFileName,
                ".jpg"
              );

            const thumbnailPath =
              `weddings/${weddingId}/photos/${albumId}/thumbnails/${thumbnailName}`;

            /*
             * SAVE THUMBNAIL TO STORAGE
             */

            const thumbnailFile =
              bucket.file(
                thumbnailPath
              );

            await thumbnailFile.save(
              thumbnailBuffer,
              {
                resumable:
                  false,

                metadata: {
                  contentType:
                    "image/jpeg",

                  cacheControl:
                    "public,max-age=31536000,immutable",
                },
              }
            );

            /*
             * UPDATE FIRESTORE
             */

            await photo.ref.update({
              thumbnailPath,

              thumbnailGeneratedAt:
                FieldValue.serverTimestamp(),
            });

            successful +=
              1;
          } catch (
            error
          ) {
            console.error(
              `Thumbnail generation failed for ${
                photo.fileName ||
                photo.id
              }:`,
              error
            );

            failures.push({
              fileName:
                photo.fileName ||
                photo.id,

              message:
                error?.message ||
                "Unknown thumbnail error.",
            });
          }
        }
      );

      /*
       * RESULT SENT BACK TO ADMIN PAGE
       */

      return {
        total:
          photos.length,

        successful,

        failed:
          failures.length,

        skipped:
          skipped.length,

        failures,

        skippedPhotos:
          skipped,
      };
    }
  );

/*
 * =========================================================
 * CONCURRENCY
 * =========================================================
 *
 * Runs several photos at the same time
 * without starting the entire album at once.
 *
 * This version intentionally avoids
 * `while (true)` so ESLint's
 * no-constant-condition rule is happy.
 */

async function runWithConcurrency(
  items,
  concurrency,
  worker
) {
  let nextIndex =
    0;

  async function runWorker() {
    const currentIndex =
      nextIndex;

    nextIndex +=
      1;

    /*
     * No more items for this worker.
     */

    if (
      currentIndex >=
      items.length
    ) {
      return;
    }

    /*
     * Process one item.
     */

    await worker(
      items[
        currentIndex
      ]
    );

    /*
     * Then ask this worker to take
     * another item.
     */

    await runWorker();
  }

  const workerCount =
    Math.min(
      concurrency,
      items.length
    );

  const workers =
    Array.from(
      {
        length:
          workerCount,
      },

      () =>
        runWorker()
    );

  await Promise.all(
    workers
  );
}

/*
 * =========================================================
 * HEIC HELPERS
 * =========================================================
 */

function isHeicPhoto(
  photo
) {
  const fileName =
    String(
      photo.fileName ||
        ""
    ).toLowerCase();

  const storagePath =
    String(
      photo.storagePath ||
        ""
    ).toLowerCase();

  const contentType =
    String(
      photo.contentType ||
        ""
    ).toLowerCase();

  return (
    contentType.includes(
      "heic"
    )
    ||
    contentType.includes(
      "heif"
    )
    ||
    fileName.endsWith(
      ".heic"
    )
    ||
    fileName.endsWith(
      ".heif"
    )
    ||
    storagePath.endsWith(
      ".heic"
    )
    ||
    storagePath.endsWith(
      ".heif"
    )
  );
}

/*
 * displayPath is also set for normal
 * JPEG uploads, where it simply equals
 * storagePath.
 *
 * We only consider it a real display
 * copy when it points somewhere else.
 */

function hasSeparateDisplayCopy(
  photo
) {
  return Boolean(
    photo.displayPath
    &&
    photo.displayPath !==
      photo.storagePath
  );
}

/*
 * =========================================================
 * PATH HELPERS
 * =========================================================
 */

function getStorageFileName(
  storagePath
) {
  return String(
    storagePath ||
      ""
  )
    .split("/")
    .pop();
}

function replaceExtension(
  fileName,
  extension
) {
  const dot =
    fileName.lastIndexOf(
      "."
    );

  if (
    dot ===
    -1
  ) {
    return `${fileName}${extension}`;
  }

  return `${fileName.slice(
    0,
    dot
  )}${extension}`;
}